# Site settings
timezone: America/Chicago
title: Cerner Splunk Cookbook
description: > 
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
baseurl: "/cerner_splunk"  
url: "http://engineering.cerner.com"
# Build settings
markdown: kramdown
